spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/flight?currentSchema=flight_service'
    username: 'admin'
    password: 'admin'
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
server:
  port: 8080