package com.hotelservice.hotelApi.constant;

public enum CommonExceptionStatus {
    DEFAULT,
    INTERNAL_SERVER_ERROR,
    HOTEL_NOT_FOUND,
    NO_HOTELS_FOUND,
    HOTEL_DTO_NOT_VALID,
    ROOM_DTO_NOT_VALID,
    ADDITIONAL_SERVICE_NOT_FOUND,
    NO_ROOMS_FOUND,
    NO_ADDITIONAL_SERVICE_FOUND,
    EXCURSIONS_NOT_FOUND,
    ROOM_NOT_FOUND
}
